merging scripts into incoming just to clean things up. (#42)
* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Create rsync_expect_script

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update rsync_expect_script

* Update from_bluehost_to_github.yml

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update from_bluehost_to_github.yml

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

* Update rsync_expect_script

This is mostly working!

* Update rsync_expect_script

we're going live!

* Update rsync_expect_script

* Update rsync_expect_script

removed --delete flag on rsync.  Not sure.
removed *.bak exclude as it didn't work.

* Update from_bluehost_to_github.yml

* Update rsync_expect_script

* Update from_bluehost_to_github.yml

* Update from_bluehost_to_github.yml

* Update ftp_expect_script

* Update from_bluehost_to_github.yml

diff --git a/.github/workflows/from_bluehost_to_github.yml b/.github/workflows/from_bluehost_to_github.yml
--- a/.github/workflows/from_bluehost_to_github.yml
+++ b/.github/workflows/from_bluehost_to_github.yml
@@ -3,7 +3,7 @@ name: from_bluehost_to_github
 on:
   schedule:
     # * is a special character in YAML so you have to quote this string
-    #- cron:  '*/30 * * * *'
+    - cron:  '*/30 * * * *'
   workflow_dispatch:
     # inputs:
     #   debug_enabled:
@@ -30,34 +30,36 @@ jobs:
       - name: Clone campbellluggblackwell.com from github to ./source
         run: |
              echo "GITHUB_REF = $GITHUB_REF"
-             # export BRANCH=`cut -d/ -f3 <<< $GITHUB_REF`
-             export BRANCH=incoming
-             echo "BRANCH = $BRANCH"
-             git clone --single-branch --branch ${BRANCH} https://${{ secrets.API_TOKEN_GITHUB }}@github.com/campbellluggblackwell/campbellluggblackwell.com.git source
-
-      - name: Get Bluehost files
-        timeout-minutes: 10
-        run: |
-            cd ./source/incoming/
-            chmod +x ../.github/workflows/ftp_expect_script
-            set -f
-            ../.github/workflows/ftp_expect_script $BLUEHOST_USERNAME $BLUEHOST_PASSWORD *.png
-            ../.github/workflows/ftp_expect_script $BLUEHOST_USERNAME $BLUEHOST_PASSWORD *.jpg
-            ../.github/workflows/ftp_expect_script $BLUEHOST_USERNAME $BLUEHOST_PASSWORD *.jpeg
-            ../.github/workflows/ftp_expect_script $BLUEHOST_USERNAME $BLUEHOST_PASSWORD *.css
-            ../.github/workflows/ftp_expect_script $BLUEHOST_USERNAME $BLUEHOST_PASSWORD *.js
-            ../.github/workflows/ftp_expect_script $BLUEHOST_USERNAME $BLUEHOST_PASSWORD *.html
-      - name: Commit and push bluehost files to github
-        run: |
-            cd ./source/incoming/
-            git add --all
-            git commit -am "Automatic upload from action from_bluehost_to_github.yml"
-            git push || true
-            
-      # Enable tmate debugging of manually-triggered workflows if the input option was provided
+             git clone --single-branch --branch main https://${{ secrets.API_TOKEN_GITHUB }}@github.com/campbellluggblackwell/campbellluggblackwell.com.git main
+             git clone --single-branch --branch incoming https://${{ secrets.API_TOKEN_GITHUB }}@github.com/campbellluggblackwell/campbellluggblackwell.com.git incoming
+          
       - name: Setup tmate session (if debug was enabled)
         uses: mxschmitt/action-tmate@v3
         if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
+        
+      - name: Get Bluehost files
+        timeout-minutes: 10
+        run: |
+            ls
+            chmod +x main/.github/workflows/rsync_expect_script
+            main/.github/workflows/rsync_expect_script $BLUEHOST_USERNAME $BLUEHOST_PASSWORD
+            # Cleanup
+            rm -Rf ./main
+            cd ./incoming/website/
+            rm -Rf *.bak
+            rm -Rf .htaccess
+            rm -Rf .ftp*
+            
+
+      - name: Commit and push bluehost files to github
+        run: |
+            cd ./incoming/website/
+            git status
+            git add --all
+            git commit -am "Automatic upload from action from_bluehost_to_github.yml" || true
+            git push || true
+            
+
             
 
       
